source 'https://rubygems.org'

gem 'rails'
gem 'sass-rails'
gem 'uglifier'
gem 'coffee-rails'
gem 'jquery-rails'

gem 'jbuilder'
gem 'puma'
gem 'turbolinks'
gem 'purecss-rails'
gem "paperclip", "3.5.4"
gem 'normalize-rails'
gem 'bootstrap-sass'
gem 'sdoc'

group :development, :test do
  
  gem 'sqlite3', '1.3.11'
  gem 'byebug',  '9.0.0', platform: :mri
end

group :development do
  gem 'web-console',           '3.1.1'
  gem 'listen',                '3.0.8'
  gem 'spring',                '1.7.2'
  gem 'spring-watcher-listen', '2.0.0'
end

group :test do
  gem 'rails-controller-testing'
  gem 'minitest-reporters'
  gem 'guard'                    
  gem 'guard-minitest'          
end


group :production do
  gem 'pg', '0.18.4'
  ruby "2.3.0"
  gem 'rails_12factor'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]